version: "2"
run:
  timeout: 10m10s
  skip-files:
    - ".*_gen.go"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  default: none
  enable:
    - errcheck
    - gocritic
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - unconvert
    - unused
    - whitespace

  exclusions:
    paths:
      - ".*_gen\\.go"
    generated: strict

  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln

formatters:
  enable:
    - gofmt
    - goimports

  # don't enable:
  #  - asciicheck
  #  - depguard
  #  - dogsled
  #  - dupl
  #  - funlen
  #  - gochecknoinits
  #  - gochecknoglobals
  #  - gocognit
  #  - goconst
  #  - gocyclo
  #  - gomnd
  #  - godot
  #  - godox
  #  - goerr113
  #  - lll
  #  - prealloc
  #  - revive
  #  - stylecheck
  #  - staticcheck
  #  - structcheck
  #  - testpackage
  #  - unparam
  #  - wsl
