// Copyright 2017-2020 The Usacloud Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by 'github.com/sacloud/usacloud/tools/gen-cli-params-v1'; DO NOT EDIT

package disk

import (
	service "github.com/sacloud/libsacloud/v2/helper/service/disk"
	"github.com/sacloud/usacloud/pkg/cmd/base"
	"github.com/sacloud/usacloud/pkg/cmd/conv"
	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

func (p *ListParameter) BuildFlags(fs *pflag.FlagSet) {
	fs.StringSliceVarP(&p.Names, "names", "", p.Names, "")
	fs.StringSliceVarP(&p.Tags, "tags", "", p.Tags, "")
	fs.IntVarP(&p.Count, "count", "", p.Count, " (aliases: ls, find, select)")
	fs.IntVarP(&p.From, "from", "", p.From, " (aliases: ls, find, select)")
	fs.StringVarP(&p.OutputType, "output-type", "o", p.OutputType, "Output format: one of the following [table/json/yaml] (aliases: ls, find, select)")
	fs.BoolVarP(&p.Quiet, "quiet", "q", p.Quiet, "Output IDs only")
	fs.StringVarP(&p.Format, "format", "", p.Format, "Output format in Go templates (aliases: ls, find, select)")
	fs.StringVarP(&p.FormatFile, "format-file", "", p.FormatFile, "Output format in Go templates(from file)")
	fs.StringVarP(&p.Query, "query", "", p.Query, "JMESPath query")
	fs.StringVarP(&p.QueryFile, "query-file", "", p.QueryFile, "JMESPath query(from file)")
	fs.SetNormalizeFunc(p.normalizeFlagName)
}

func (p *ListParameter) normalizeFlagName(_ *pflag.FlagSet, name string) pflag.NormalizedName {
	switch name {
	case "max":
		name = "count"
	case "limit":
		name = "count"
	case "offset":
		name = "from"
	case "out":
		name = "output-type"
	case "fmt":
		name = "format"
	}
	return pflag.NormalizedName(name)
}

func (p *ListParameter) CategorizedFlagSets(cmd *cobra.Command) []*base.FlagSet {
	var sets []*base.FlagSet
	{
		var fs *pflag.FlagSet
		fs = pflag.NewFlagSet("filter", pflag.ContinueOnError)
		fs.AddFlag(cmd.LocalFlags().Lookup("names"))
		fs.AddFlag(cmd.LocalFlags().Lookup("tags"))
		fs.AddFlag(cmd.LocalFlags().Lookup("count"))
		fs.AddFlag(cmd.LocalFlags().Lookup("from"))
		sets = append(sets, &base.FlagSet{
			Title: "Filter options",
			Flags: fs,
		})
	}
	{
		var fs *pflag.FlagSet
		fs = pflag.NewFlagSet("output", pflag.ContinueOnError)
		fs.AddFlag(cmd.LocalFlags().Lookup("output-type"))
		fs.AddFlag(cmd.LocalFlags().Lookup("quiet"))
		fs.AddFlag(cmd.LocalFlags().Lookup("format"))
		fs.AddFlag(cmd.LocalFlags().Lookup("format-file"))
		fs.AddFlag(cmd.LocalFlags().Lookup("query"))
		fs.AddFlag(cmd.LocalFlags().Lookup("query-file"))
		sets = append(sets, &base.FlagSet{
			Title: "Output options",
			Flags: fs,
		})
	}

	return sets
}

func (p *ListParameter) ServiceRequest() (*service.FindRequest, error) {
	req := &service.FindRequest{}
	return req, conv.ConvertTo(p, req)
}
