// Code generated by 'github.com/sacloud/usacloud/tools/gen-command-completion'; DO NOT EDIT

package command

func IconCreateCompleteArgs(ctx Context, params *CreateIconParam, cur, prev, commandName string) {

}
