// Code generated by 'github.com/sacloud/usacloud/tools/gen-command-completion'; DO NOT EDIT

package command

import (
	"fmt"
	"github.com/sacloud/usacloud/define"
	"github.com/sacloud/usacloud/schema"
)

func SimpleMonitorUpdateCompleteFlags(ctx Context, params *UpdateSimpleMonitorParam, flagName string, currentValue string) {
	var comp schema.SchemaCompletionFunc

	switch flagName {
	case "delay-loop":
		comp = define.Resources["SimpleMonitor"].Commands["update"].Params["delay-loop"].CompleteFunc
	case "description", "desc":
		comp = define.Resources["SimpleMonitor"].Commands["update"].Params["description"].CompleteFunc
	case "dns_excepted":
		comp = define.Resources["SimpleMonitor"].Commands["update"].Params["dns_excepted"].CompleteFunc
	case "dns_qname":
		comp = define.Resources["SimpleMonitor"].Commands["update"].Params["dns_qname"].CompleteFunc
	case "email-type":
		comp = define.Resources["SimpleMonitor"].Commands["update"].Params["email-type"].CompleteFunc
	case "enabled":
		comp = define.Resources["SimpleMonitor"].Commands["update"].Params["enabled"].CompleteFunc
	case "host-header":
		comp = define.Resources["SimpleMonitor"].Commands["update"].Params["host-header"].CompleteFunc
	case "icon-id":
		comp = define.Resources["SimpleMonitor"].Commands["update"].Params["icon-id"].CompleteFunc
	case "id":
		comp = define.Resources["SimpleMonitor"].Commands["update"].Params["id"].CompleteFunc
	case "notify-email":
		comp = define.Resources["SimpleMonitor"].Commands["update"].Params["notify-email"].CompleteFunc
	case "path":
		comp = define.Resources["SimpleMonitor"].Commands["update"].Params["path"].CompleteFunc
	case "port":
		comp = define.Resources["SimpleMonitor"].Commands["update"].Params["port"].CompleteFunc
	case "protocol":
		comp = define.Resources["SimpleMonitor"].Commands["update"].Params["protocol"].CompleteFunc
	case "response-code":
		comp = define.Resources["SimpleMonitor"].Commands["update"].Params["response-code"].CompleteFunc
	case "slack-webhook":
		comp = define.Resources["SimpleMonitor"].Commands["update"].Params["slack-webhook"].CompleteFunc
	case "tags":
		comp = define.Resources["SimpleMonitor"].Commands["update"].Params["tags"].CompleteFunc
	case "output-type", "out":
		comp = schema.CompleteInStrValues("json", "csv", "tsv")
	}

	if comp != nil {
		words := comp(ctx, currentValue)
		for _, w := range words {
			fmt.Println(w)
		}
	}
}
