// Code generated by 'github.com/sacloud/usacloud/tools/gen-command-completion'; DO NOT EDIT

package command

import (
	"fmt"
	"github.com/sacloud/usacloud/define"
	"github.com/sacloud/usacloud/schema"
)

func DNSUpdateCompleteFlags(ctx Context, params *UpdateDNSParam, flagName string, currentValue string) {
	var comp schema.SchemaCompletionFunc

	switch flagName {
	case "description", "desc":
		comp = define.Resources["DNS"].Commands["update"].Params["description"].CompleteFunc
	case "icon-id":
		comp = define.Resources["DNS"].Commands["update"].Params["icon-id"].CompleteFunc
	case "id":
		comp = define.Resources["DNS"].Commands["update"].Params["id"].CompleteFunc
	case "tags":
		comp = define.Resources["DNS"].Commands["update"].Params["tags"].CompleteFunc
	}

	if comp != nil {
		words := comp(ctx, currentValue)
		for _, w := range words {
			fmt.Println(w)
		}
	}
}
