#!/bin/bash

travis encrypt GPG_PASSPHRASE=$GPG_PASSPHRASE -a
travis encrypt GITHUB_TOKEN=$GITHUB_TOKEN -a
travis encrypt SACLOUD_OJS_ACCESS_KEY_ID=$SACLOUD_OJS_ACCESS_KEY_ID -a
travis encrypt SACLOUD_OJS_SECRET_ACCESS_KEY=$SACLOUD_OJS_SECRET_ACCESS_KEY -a
travis encrypt SAKURACLOUD_ACCESS_TOKEN=SAKURACLOUD_ACCESS_TOKEN -a
travis encrypt SAKURACLOUD_ACCESS_TOKEN_SECRET=$SAKURACLOUD_ACCESS_TOKEN_SECRET -a