# from https://docs.github.com/en/free-pro-team@latest/actions/guides/publishing-docker-images#publishing-images-to-github-packages
name: Publish Docker image(dev)
on:
  push:
    branches:
      - main
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry(dev)
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push to GitHub Container Registry
        uses: docker/build-push-action@v3
        with:
          tags: ghcr.io/sacloud/usacloud:dev
          push: true