name: Tests
on: [push, pull_request]
env:
  GOPROXY: https://proxy.golang.org
jobs:
  lint-text:
    name: lint-text
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: 'go.mod'

      - name: Setup tools
        run: |
          make tools

      - name: make lint-text
        run:  |
          make lint-text
  lint-go:
    name: lint-go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: 'go.mod'

      - name: Setup tools
        run: | 
          make tools

      - name: make lint-go
        run:  |
          # Explicitly set GOROOT to avoid golangci-lint/issues/3107
          GOROOT=$(go env GOROOT)
          export GOROOT
          make lint-go

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: 'go.mod'

      - name: Setup tools
        run: | 
          make tools

      - name: make test
        run: |
          make test
